default: &default
  DB_NAME: "#{app_name}"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  USERNAME: "postgres"
  MAILER_DEFAULT_HOST: "localhost"
  MAILER_DEFAULT_PORT: "3000"
  MAILER_SENDER: "Test <noreply@nimbl3.co>"
  AVAILABLE_LOCALES: "en"
  DEFAULT_LOCALE: "en"
  FALLBACK_LOCALES: "en"

development:
  <<: *default

test:
  <<: *default
  TEST_RETRY: "0"
